### ISSUE TITLE
Custom start angle

### ISSUE THREAD

**Issue by squirelo** [spaceymonk/react-radial-menu#3]
Hi,

I would like to know if there is a way to define a custom start angle to set the position of the first item at a specific radius.

Thx a lot for your work

**Comment by spaceymonk** [comment]
Hi,
Unfortunately, you cannot give custom start angles. Best you can do is that apply rotation to menu and re-order the `MenuItem` components.

You can implement rotation using CSS:
```css
:root {
  --__reactRadialMenu__rotate: 45deg;
}
.__rrm-menu {
  rotate: var(--__reactRadialMenu__rotate);
}
.__rrm-content {
  rotate: calc(-1 * var(--__reactRadialMenu__rotate));
}
```
Results in:
![image](https://github.com/spaceymonk/react-radial-menu/assets/44543385/bf67220e-3bd8-4311-8012-068f77d3a62d)

Then, if necessary, you can handle the amount of rotation programmatically:
```js
document.documentElement.style.setProperty("--__reactRadialMenu__rotate", "60deg");
```

Here is an another example using `display: hide` on certain `MenuItem` and rotation of `-90deg` to customize the look of the menu:
```css
.hide {
  display: none;
}
```
```jsx
 <Menu
    centerX={position.x}
    centerY={position.y}
    innerRadius={40}
    outerRadius={150}
    show={show}
    animation={["fade", "scale"]}
    animationTimeout={300}
    theme="dark"
    drawBackground
    animateSubMenuChange
    >
    <MenuItem onItemClick={handleItemClick} data="1. Item"> 1. Item </MenuItem>
    <MenuItem onItemClick={handleItemClick} data="dummy" className="hide">
      Dummy item will not show up
    </MenuItem>
    
    <SubMenu
      onDisplayClick={handleDisplayClick}
      onItemClick={handleSubMenuClick}
      itemView="2. Sub Menu"
      data="2. Sub Menu"
      displayPosition="center"
    >
    {/* ... */}
```

![image](https://github.com/spaceymonk/react-radial-menu/assets/44543385/3ff150cc-bb97-4c2b-8b4a-174c12ea9450)
